on :
    workflow_dispatch
jobs:
    flow:
     runs-on: ubuntu-latest
     steps:
         - name : print something
           run : echo " you have asked to print something right??"

    start:
        runs-on: ubuntu-latest
        steps: 
         - name : print the files 
           run : ls -ltr