name: firstexample
on : push
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
         - name : checkout the actions
           uses : actions/checkout@v4
         - name : excuting the shell scripting
           run : ./script.sh
         - name : get the list of iteams
           run : ls -ltr
        
