name: firstexample
on : push
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
         - name : checkout the actions
           uses : actions/checkout@v4
         
         - name : install the cowsay
           run : sudo apt install cowsay -y
         - name : run cowsay
           run : cowsay "hellow SriHari_Boligarla"
         - name : get the list of iteams
           run : ls -ltr
        
